### ISSUE TITLE
Backspacing

### ISSUE THREAD

**Issue by MalloryEaton** [angular-ui/ui-mask#2]
My mask is "0.99". When there is no input, if I press backspace, it seems to append zeros. 
Basically, I have a similar problem to this: https://github.com/angular-ui/ui-utils/issues/271

**Comment by z0rbas** [comment]
The original Issue: https://github.com/angular-ui/ui-utils/issues/271
Don't know why this was closed right after opening, but the problem persists.

With ui-mask="QT**********" you can enter any characters and it will work fine. After erasing all the characters with backspace and then continuing  to press backspace the value will start filling up with the first static character of the mask, i.e. "QTQQQQQQ". This can be reproduced on the ui-mask html preview page.

**Comment by PowerKiKi** [comment]
Should be fixed via #98

**Comment by mlabarca** [comment]
This problem persists for me exactly as described in android.
