### ISSUE TITLE
Mask with placeholder

### ISSUE THREAD

**Issue by dshep4** [angular-ui/ui-mask#4]
Using a mask with a placeholder doesn't seem to work properly. For example if I have a phone number mask ``(999) 999-9999`` and a placeholder ``Phone Number`` I get the following result when trying to enter phone number ``123 456 7891``:

``P123e 456b78.``

**Comment by ovargas** [comment]
I have the same issue

**Comment by colingreene28** [comment]
+1

This issue was present in the old angular-ui/ui-utils mask module. This is a fairly big bug that has slipped through the net IMHO.

Which is more likely: a fix by an admin or a concerned citizen? If it's the latter, it's something I might be able to look at over the weekend.

**Comment by PowerKiKi** [comment]
Indeed, it should have been solved for a long time now. However I am not familiar enough with the codebase to do it myself. So it will most likely require a PR from someone else.

We used to have a PR that seemed to be working, according to user reports, but lack tests and demo: https://github.com/angular-ui/ui-utils/pull/353

I didn't try it out myself, but this might be an interesting starting point if you are willing to work on that...

**Comment by colingreene28** [comment]
I actually pulled this down locally but it didn't seem to work for me. However as you said it lacked tests/demo so I could have assumed some details and got mixed up. It seemed to work for other people based on the comments at least so yeah could be a good place to start.

Will check back in if I get anywhere

**Comment by PowerKiKi** [comment]
If necessary, a complete rewrite of ``ui-mask`` would be acceptable IMHO, especially if it also tackles what seems to be severe compatibility issues (see #5). It seems the codebase is quite brittle unfortunately.

Also, just to clarify, I am not the author, nor the maintainer, not even a user, of this lib. I merely triage bug and merge well-written/tested PR.

**Comment by colingreene28** [comment]
Quick update.

One of the big things that doesn't work me and my usage of ui-mask is the fact that there is a default placeholder applied when you define a mask. So for example, if you have the following mask:

```
ui-mask="999-999"
``` 

you will automagically get this placeholder on your input:

```html
<input ng-model="x" ui-mask="999-999" placeholder="___-___"/>
```

This is NOT how I would expect this to work. Why would it assume you want a default placeholder? Also, when you actually provide an actual placeholder it makes a bastardized amalgamation of the two, which corresponds to the OP bug above. I'm not sure who made this decision or how these decisions come about on a community project.... Does someone come up with an initial spec or does functionality just organically happen over time?

This is my first time attempting to contribute to a project like this, making wholesale changes would not be my preferred modus operandi. However I looked at trying to step away from the default placeholder. What I came away with was that masking and the placeholder were tightly coupled and removing it required much more time and effort than the quick(ish) fix that I invisioned it would take.

Maybe I am off thinking that this is the way it should work or maybe there is a legitamate reason for all this. Maybe someone with more hands on experience with the code base could talk to this? @PowerKiKi Maybe a rewrite with a clear spec could be a viable option, but it's not something I can commit to myself at the moment though.

**Comment by PowerKiKi** [comment]
I assumed it would not be that simple, and that this project grew organically.

My idea (without looking at the code), was that we could save the original value of placeholder (if any), and reassign that original value, if/when the user did not input anything (or deleted it). That would mostly keep the same behavior as now, but still allowing to specify a placeholder.

However after a very quick glance at the code I came up with the same conclusion as you: placeholder is somewhat heavily used for masking and maybe not in the cleanest way it could have been.

Like I said I won't have time, nor interest to be honest, in solving that. So if you don't either, we'll just wait for someone else to care enough about it ;-)

**Comment by chadwhitaker** [comment]
+1

**Comment by artlogic** [comment]
:+1:

**Comment by fabiowitt** [comment]
+1

**Comment by dimrsilva** [comment]
I think we can close this one.

**Comment by PowerKiKi** [comment]
Solved via #24

**Comment by chadwhitaker** [comment]
@dimrsilva @PowerKiKi It appears there is still an issue with `ui-placeholder-mask`.

I created this demo here: http://plnkr.co/edit/TpN0hdkHZlXR9wSr71Lu?p=preview

You can see that the top version works without a `placeholder`. But, the second version with the `placeholder` and `ui-mask-placeholder` doesn't work when the `ui-mask` is set directly. 

If you pass the `ui-mask` via a scope it works fine. This holds true on the [github demo](http://htmlpreview.github.io/?https://github.com/angular-ui/ui-mask/master/demo/index.html) since the `ui-mask` is being passed via the buttons below.

**Comment by dimrsilva** [comment]
It's related with #25. Thanks for your plunk. It'll help.

**Comment by msorce** [comment]
Hey everyone, I was able to solve this by having the ui-mask set as :
`ui-mask="(999) 999-9999"`

and the placeholder set:
`placeholder="(___) ___-____"`

then on load with jQuery I did this:
`$(yourMaskedElement).attr('placeholder', 'ENTER MOBILE NUMBER'); `

**Comment by pouletfou** [comment]
Following msorce tip about jquery, I created a small directive to replace ui-mask-placeholder.

Just adding 
`ubt-mask-placeholder="{{"somestring"}}`
OR  when using angular-translate :
`ubt-mask-placeholder="{{"somestring"` | translate}}



(function () {
  'use strict';
  angular
          .module('app')
          .directive("ubtMaskPlaceholder", ubtMaskPlaceholder);

  function ubtMaskPlaceholder() {
    return {
      restrict: 'A',
      scope: {
        placeholder: '@ubtMaskPlaceholder'
      },
      link: function (scope, elem, attrs, uiMask) {
        $(function(){
          $(elem).attr('placeholder',scope.placeholder);
        })        
        scope.$on('$translateChangeSuccess', function () {
          $(elem).attr('placeholder',scope.placeholder);
        });
      }
    };
  }

})();
`
